import React from 'react';
import Layout from '@/components/layout/Layout';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Easy Cooking | Салати',
  description: 'Generated by create next app',
};

const SaladsPage = () => {
  return <Layout>SaladsPage</Layout>;
};

export default SaladsPage;
