import React from 'react';
import Layout from '@/components/layout/Layout';
import DishCard from '@/components/dishCard/DishCard';
import DishCardWrap from '@/components/dishCard/DishCardWrap';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Easy Cooking | Пасти',
  description: 'Generated by create next app',
};
const Pastas = () => {
  return (
    <Layout>
      <DishCardWrap>
        <DishCard
          title="Паста карбонара"
          dishes={4}
          rate={3.5}
          time="20 хв"
          src={'/carbonara.jpg'}
        />
      </DishCardWrap>
    </Layout>
  );
};

export default Pastas;
